id: I88A2358A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T01:26:47+00:00'
last_modified: '2022-06-07T16:20:19.991638+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23421
  title: ཆེད་དུ་བརྗོད་པའི་ཚོམས་ཀྱི་རྣམ་པར་འགྲེལ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4C1B:
      image_group_id: I1KG23495
      title: ''
      total_pages: 156
      order: 1
      base_file: 4C1B.txt
    04BC:
      image_group_id: I1KG23496
      title: ''
      total_pages: 120
      order: 2
      base_file: 04BC.txt
    DEF6:
      image_group_id: I1KG23497
      title: ''
      total_pages: 136
      order: 3
      base_file: DEF6.txt
    6F36:
      image_group_id: I1KG23498
      title: ''
      total_pages: 148
      order: 4
      base_file: 6F36.txt
    EC19:
      image_group_id: I1KG23499
      title: ''
      total_pages: 170
      order: 5
      base_file: EC19.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
